### ISSUE TITLE
cannot connect to X server localhost:11.0

### ISSUE THREAD

**Issue by kiitaamuuraa** [peteanderson80/Matterport3DSimulator#102]
Firstly, I appreciate your great work on this project.
I have been setting up my docker environment following your [instruction](https://github.com/peteanderson80/Matterport3DSimulator/#installation--build-instructions), and am trying to run the instructive demo. I encountered an error, whose message is `cannot connect to X server localhost:11.0`on running `python3 src/driver/driver.py`. 
It would be great if you could help with the issue.

**Comment by kiitaamuuraa** [comment]
I tried to execute the following code and failed to connect to X server on a docker container.
```
root@196ad3b0a158:~/mount/Matterport3DSimulator/build# python3Python 3.6.9 (default, Jan 26 2021, 15:33:00) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
>>> cv2.namedWindow('Python RGB')
: cannot connect to X server 
```

Also, I made sure the code, `cv2.namedWindow('Python RGB')`, had worked without docker.

**Comment by chenguanqi** [comment]
Hi, I have the same problem. Do you solve this problem?

**Comment by kiitaamuuraa** [comment]
Yes, I did; I followed the following instruction 
https://stackoverflow.com/questions/48235040/run-x-application-in-a-docker-container-reliably-on-a-server-connected-via-ssh-w
