### ISSUE TITLE
How to get equirectangular image?

### ISSUE THREAD

**Issue by MarSaKi** [peteanderson80/Matterport3DSimulator#104]

**Comment by MarSaKi** [comment]
tttt

**Comment by jdiazram** [comment]
Hi @MarSaKi, Could you solve it? How can I get an equirectangular image from a viewpoint?

**Comment by MarSaKi** [comment]
> Hi @MarSaKi, Could you solve it? How can I get an equirectangular image from a viewpoint?

Unfortunately, I haven't solved it yet.
