### ISSUE TITLE
Build the docker image error

### ISSUE THREAD

**Issue by LiHui1116** [peteanderson80/Matterport3DSimulator#113]
I follow the readme until 'Build the docker image' step, after imput the command 'docker build -t mattersim:9.2-devel-ubuntu18.04 .' I got an error

Get:357 http://archive.ubuntu.com/ubuntu bionic/main amd64 libglm-dev all 0.9.9~a2-2 [163 kB]
Get:358 http://archive.ubuntu.com/ubuntu bionic/main amd64 libjsoncpp-dev amd64 1.7.4-3 [85.3 kB]
Get:359 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libosmesa6 amd64 20.0.8-0ubuntu1~18.04.1 [2641 kB]
Get:360 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libosmesa6-dev amd64 20.0.8-0ubuntu1~18.04.1 [8828 B]
Get:361 http://archive.ubuntu.com/ubuntu bionic/universe amd64 proj-bin amd64 4.9.3-2 [32.3 kB]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/universe/f/ffmpeg/libavcodec57_3.4.11-0ubuntu0.1_amd64.deb  Connection failed [IP: 91.189.91.39 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/universe/f/fyba/libfyba0_4.1.1-3_amd64.deb  Connection failed [IP: 91.189.91.39 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/libx/libxpm/libxpm4_3.5.12-1_amd64.deb  Connection failed [IP: 185.125.190.39 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/universe/f/freexl/libfreexl1_1.0.5-1_amd64.deb  Connection failed [IP: 91.189.91.39 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/universe/g/geos/libgeos-3.6.2_3.6.2-1build2_amd64.deb  Connection failed [IP: 185.125.190.39 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/j/jbigkit/libjbig-dev_2.1-3.1build1_amd64.deb  Connection failed [IP: 185.125.190.39 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Fetched 213 MB in 2min 2s (1749 kB/s)
The command '/bin/sh -c apt-get update && apt-get install -y wget doxygen curl libjsoncpp-dev libepoxy-dev libglm-dev libosmesa6 libosmesa6-dev libglew-dev libopencv-dev python-opencv python3-setuptools python3-dev python3-pip' returned a non-zero code: 100

I tried google and bing search this question , one answer said using the file dockerfile.txt, but I don't know the whole contents in dockerfile. So my question is, what is the command in the file dockerfile?

**Comment by RunweiSitu** [comment]
@LiHui1116 Could you tell me how to solve this problem? I met it also.
