### ISSUE TITLE
Docker mount

### ISSUE THREAD

**Issue by Routine113** [peteanderson80/Matterport3DSimulator#123]
I used a remote server to perform operations, and then when I run ./scripts/downsize_ skybox. Py, 
an error occurred: FileNotFoundError: [Erro 2] No such file or directory: '/data3/wuyifei/PatterPort3D/v1/scans/17DRP5sb8fy/undorted_ camera_ parameters/17DRP5sb8fy.conf'.
But I'm sure I have this folder. The problem is that Docker cannot access this folder. But I dont know how to make prompt ""Note that if is a remote sshfs mount, you will need to mount it with the -o allow_root option or the docker container won't be able to access this directory.""
I wonder if you have a solution? Thank U very much!

**Comment by bjzhb666** [comment]
I am facing the same problem? How to solve it? Thanks!

**Comment by Routine113** [comment]
> 

I'm ashamed that I haven't found a solution yet. Docker's knowledge is not very clear. If you make progress, I hope you can tell me

**Comment by Routine113** [comment]
> 

I'm ashamed that I haven't found a solution yet. Docker's knowledge is not very clear. If you make progress, I hope you can tell me

**Comment by staale92** [comment]
Hi,
I don't think it is a problem with Docker, but rather with the path to the scans directory. Have you verified that you have the required data downloaded, and that `MATTERPORT_DATA_DIR` is set to the directory containing the Matterport scan folders (`../Matterport3D/data/v1/scans`)? Notice that the downloaded files under each scan folder should be first unzipped (as mentioned in the instructions and in #85) and that depending on how you unzip the files you could accidentally create subfolders with the same name as the main folder. Running something like `for k in $(find ./ -type f -name '*.zip') ; do unzip $k ; done` from the `../Matterport3D/data/v1/scans` directory should work fine.

**Comment by Routine113** [comment]
> Hi, I don't think it is a problem with Docker, but rather with the path to the scans directory. Have you verified that you have the required data downloaded, and that `MATTERPORT_DATA_DIR` is set to the directory containing the Matterport scan folders (`../Matterport3D/data/v1/scans`)? Notice that the downloaded files under each scan folder should be first unzipped (as mentioned in the instructions and in #85) and that depending on how you unzip the files you could accidentally create subfolders with the same name as the main folder. Running something like `for k in $(find ./ -type f -name '*.zip') ; do unzip $k ; done` from the `../Matterport3D/data/v1/scans` directory should work fine.

Oh，Thank you very much for your patient answer！！
