### ISSUE TITLE
Rendered images are black (all pixels are 0s)

### ISSUE THREAD

**Issue by Ber666** [peteanderson80/Matterport3DSimulator#131]
![image](https://github.com/peteanderson80/Matterport3DSimulator/assets/46735523/640fba57-59dc-48ab-ba28-91771bbdc5b9)

It seems image rendering is the only problem. I tested makeAction and other states changed accordingly.

What's more unbelievable is that I could get the desired images several hours ago, and I didn't know I modified anything...

**Comment by Ber666** [comment]
setting `sim.setCacheSize(2)` fixes this problem😅 Everything in this repo is just too magic to me

**Comment by LemonZhong** [comment]
I agree. Too magic😅

**Comment by WendyeeWang** [comment]
😅

**Comment by jdiazram** [comment]
Hello @Ber666, is it possible to share the code? And how did you install MatterportSim? Local?
Thank you
