### ISSUE TITLE
Could not open skybox RGB files

### ISSUE THREAD

**Issue by GalaxyS1ayer** [peteanderson80/Matterport3DSimulator#138]
Can anyone tell me how to fix this? I checked the dataset I downloaded and there is no such image in.
MatterSim: Could not open skybox RGB files at: ../Matterport3DSimulator/data/v1/scans/17DRP5sb8fy/matterport_skybox_images/10c252c90fa24ef3b698c6f54d984c5c_skybox_small.jpg

**Comment by mn-pang** [comment]
I have the same problem.

**Comment by CelestinoMelodyLumiere** [comment]
> Can anyone tell me how to fix this? I checked the dataset I downloaded and there is no such image in. MatterSim: Could not open skybox RGB files at: ../Matterport3DSimulator/data/v1/scans/17DRP5sb8fy/matterport_skybox_images/10c252c90fa24ef3b698c6f54d984c5c_skybox_small.jpg

May I ask if you have solved this problem? Could you please tell me the solution? Thank you very much

**Comment by GalaxyS1ayer** [comment]
Of course, you need to run the depth_to_skybox.py program to generate the depth skybox.

> > Can anyone tell me how to fix this? I checked the dataset I downloaded and there is no such image in. MatterSim: Could not open skybox RGB files at: ../Matterport3DSimulator/data/v1/scans/17DRP5sb8fy/matterport_skybox_images/10c252c90fa24ef3b698c6f54d984c5c_skybox_small.jpg谁能告诉我怎么解决这个问题？我已经检查了我下载的数据集，里面没有这样的图片。MatterSim：无法打开 skybox RGB 文件，路径为：../Matterport3DSimulator/data/v1/scans/17DRP5sb8fy/matterport_skybox_images/10c252c90fa24ef3b698c6f54d984c5c_skybox_small.jpg
> 
> May I ask if you have solved this problem? Could you please tell me the solution? Thank you very much可以问一下您解决这个问题了吗？能告诉我解决方案吗？非常感谢

Of course, you need to run the depth_to_skybox.py  to generate the depth skybox.

**Comment by CelestinoMelodyLumiere** [comment]
> Of course, you need to run the depth_to_skybox.py program to generate the depth skybox.
> 
> > > Can anyone tell me how to fix this? I checked the dataset I downloaded and there is no such image in. MatterSim: Could not open skybox RGB files at: ../Matterport3DSimulator/data/v1/scans/17DRP5sb8fy/matterport_skybox_images/10c252c90fa24ef3b698c6f54d984c5c_skybox_small.jpg谁能告诉我怎么解决这个问题？我已经检查了我下载的数据集，里面没有这样的图片。MatterSim：无法打开 skybox RGB 文件，路径为：../Matterport3DSimulator/data/v1/scans/17DRP5sb8fy/matterport_skybox_images/10c252c90fa24ef3b698c6f54d984c5c_skybox_small.jpg
> > 
> > 
> > May I ask if you have solved this problem? Could you please tell me the solution? Thank you very much可以问一下您解决这个问题了吗？能告诉我解决方案吗？非常感谢
> 
> Of course, you need to run the depth_to_skybox.py to generate the depth skybox.

I'm so so sorry. My experiment time is rather tight. I can directly ask you where the depth_to_skybox.py file is or who you need to ask for this file

**Comment by GalaxyS1ayer** [comment]
> > Of course, you need to run the depth_to_skybox.py program to generate the depth skybox.
> > > > Can anyone tell me how to fix this? I checked the dataset I downloaded and there is no such image in. MatterSim: Could not open skybox RGB files at: ../Matterport3DSimulator/data/v1/scans/17DRP5sb8fy/matterport_skybox_images/10c252c90fa24ef3b698c6f54d984c5c_skybox_small.jpg谁能告诉我怎么解决这个问题？我已经检查了我下载的数据集，里面没有这样的图片。MatterSim：无法打开 skybox RGB 文件，路径为：../Matterport3DSimulator/data/v1/scans/17DRP5sb8fy/matterport_skybox_images/10c252c90fa24ef3b698c6f54d984c5c_skybox_small.jpg
> > > 
> > > 
> > > May I ask if you have solved this problem? Could you please tell me the solution? Thank you very much可以问一下您解决这个问题了吗？能告诉我解决方案吗？非常感谢
> > 
> > 
> > Of course, you need to run the depth_to_skybox.py to generate the depth skybox.
> 
> I'm so so sorry. My experiment time is rather tight. I can directly ask you where the depth_to_skybox.py file is or who you need to ask for this file

The path to the file is /Matterport3DSimulator/scripts，you can also find it by searching the script file name directly。

**Comment by CelestinoMelodyLumiere** [comment]
> > > Of course, you need to run the depth_to_skybox.py program to generate the depth skybox.
> > > > > Can anyone tell me how to fix this? I checked the dataset I downloaded and there is no such image in. MatterSim: Could not open skybox RGB files at: ../Matterport3DSimulator/data/v1/scans/17DRP5sb8fy/matterport_skybox_images/10c252c90fa24ef3b698c6f54d984c5c_skybox_small.jpg谁能告诉我怎么解决这个问题？我已经检查了我下载的数据集，里面没有这样的图片。MatterSim：无法打开 skybox RGB 文件，路径为：../Matterport3DSimulator/data/v1/scans/17DRP5sb8fy/matterport_skybox_images/10c252c90fa24ef3b698c6f54d984c5c_skybox_small.jpg
> > > > 
> > > > 
> > > > May I ask if you have solved this problem? Could you please tell me the solution? Thank you very much可以问一下您解决这个问题了吗？能告诉我解决方案吗？非常感谢
> > > 
> > > 
> > > Of course, you need to run the depth_to_skybox.py to generate the depth skybox.
> > 
> > 
> > I'm so so sorry. My experiment time is rather tight. I can directly ask you where the depth_to_skybox.py file is or who you need to ask for this file
> 
> The path to the file is /Matterport3DSimulator/scripts，you can also find it by searching the script file name directly。

Thank you very much. I found it. I also had an error when running depth_to_skybox.py! It doesn't matter. I'm planning to start over from the beginning. May I ask whether to execute downsize_skybox.py or depth_to_skybox.py first?
