### ISSUE TITLE
i dont find skybox_small.jpg

### ISSUE THREAD

**Issue by wangjinhoon** [peteanderson80/Matterport3DSimulator#139]
```
import MatterSim
sim = MatterSim.Simulator()
sim.initialize()
# Assuming batchSize = 1
sim.newEpisode(['17DRP5sb8fy'], ['85c23efeaecd4d43a7dcd5b90137179e'], [0], [0])                                                                             
```
Hello, thank you for providing such great code.
When I run this code, I get the following error:

"ValueError: MatterSim: Could not open skybox RGB files at: ./data/v1/scans/17DRP5sb8fy/matterport_skybox_images/85c23efeaecd4d43a7dcd5b90137179e_skybox_small.jpg."

In the 17DRP5sb8fy folder that I downloaded, there are files like skybox{i}_sami.jpg, but there are no files related to skybox_small. Is there something I am missing?

**Comment by hccz95** [comment]
I met the same problem, can you help me?

**Comment by wangjinhoon** [comment]
```
./scripts/downsize_skybox.py
```
I don't remember clearly, but I think it was generated at this stage. If not, following the instructions in the README should generate it.
