### ISSUE TITLE
ImportError: No module named MatterSim

### ISSUE THREAD

**Issue by littlekobe** [peteanderson80/Matterport3DSimulator#16]
Hi,

I followed the instructions and encountered this problem "ImportError: No module named MatterSim". Any ideas about this? Thanks!

**Comment by chihyaoma** [comment]
Did you manage to fix it? I am facing the same issue.

**Comment by chihyaoma** [comment]
Looks like it's the issue with compiling while using virtual env. I pointed the path for the python in my virtual env (Conda env), and I can import the **MatterSim** successfully.

For example,
Build OpenGL version using CMake:
```
mkdir build && cd build

# change this cmake here
cmake -DPYTHON_EXECUTABLE:FILEPATH=/path/to/your/bin/python ..

make
cd ../
```

**Comment by srama2512** [comment]
Just as a side comment, the above didn't work for me for some reason. I had to manually copy over the `*.so` files from `Matterport3DSimulator/build` to my `Anaconda/lib` (even though I set the python executable as my anaconda python and added `Matterport3DSimulator/build` to `LD_LIBRARY_PATH`.
