### ISSUE TITLE
about the image feature

### ISSUE THREAD

**Issue by Warsin** [peteanderson80/Matterport3DSimulator#20]
hi,when i run the python tasks/R2R/eval.py , i could not find difference if i  provide image feature or not,did there some difference or is the image features useful ?

**Comment by peteanderson80** [comment]
When you run this script without any changes, it just evaluates some simple 'learning free' baselines, i.e. shortest-path, random, and stop (an agent that does not move). None of these results look at the image features. To test the learned agent, uncomment "eval_seq2seq()" at L127.
