### ISSUE TITLE
Rendered image all red

### ISSUE THREAD

**Issue by chihyaoma** [peteanderson80/Matterport3DSimulator#21]
Hi, 

I am running your python demo as instructed.

```bash
python src/driver/driver.py
```

But the rendered image is pretty weird. It's all red as below (no error reported). I have tested on Ubuntu 14.04 and MacOS 10.13. Both have the same result. Can you please provide some hints in solving this issue? Did I miss something? 

![image](https://user-images.githubusercontent.com/6862817/41013454-fb54116a-68fa-11e8-9573-10476680eed5.png)

**Comment by chihyaoma** [comment]
The problem is solved, but I don't yet know the actual reason. 

The whole story is that I wanted to make the compile works for both Linux and MacOS. Apparently, using **PVM** in `include` and `src/lib` causes compile error for macOS:

```bash
../Matterport3DSimulator/include/MatterSim.hpp:224:15: error: 
      expected member name or ';' after declaration specifiers
        GLint PVM;
        ~~~~~ ^
/usr/include/sys/param.h:120:13: note: expanded from macro 'PVM'
#define PVM     4
                ^
1 error generated.
make[2]: *** [CMakeFiles/tests.dir/src/test/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/tests.dir/all] Error 2
make: *** [all] Error 2

```

I thus replace all **PVM** in `include` and `src/lib` to a dummy name **PVMM**, but I commented the original lines. For example in `include/MatterSim.hpp`:
```cpp
// GLint PVM;
GLint PVMM;
```
The same goes for `MatterSim.cpp` and `vertex.sh` in `src/lib`. 

After this process, the compilation will complete without any error, but the rendered images are all red. 
The problem is due to the commented lines in `vertex.sh`

```sh
# uniform mat4 PVM;
uniform mat4 PVMM;

# ...

# gl_Position = PVM * vec4(vertex, 1.0);
gl_Position = PVMM * vec4(vertex, 1.0);
```
If I removed the commented lines, everything works fine. While I do not know the exact reason why, it seems that changing the naming of **PVM** to something else works universally for both Ubuntu and MacOS.

**Comment by mcimpoi** [comment]
I got all blue images (e.g. when running in ipython notebook).
I don't understand why -- but changing the running directory ( `%cd Matterport3DSimulator/` ) seems to fix the problem.

Hope this helps.

**Comment by achichichi** [comment]
Hello @mcimpoi : 
When I running scr/driver/driver.py in jupyter notebook, I got a valueerror about "MatterSim: Could not open navigation graph file: ./connectivity/2t7WUuJeko7_connectivity.json, is scan id valid?". I don't know how to solve this problem. Could you got the problem when running in ipython notebook and how to fix it? Thank you so much.

**Comment by Wangnaijia** [comment]
@achichichi Hi, I met the same question when running the other script. Have you solved this problem?
