### ISSUE TITLE
About the range the elevation

### ISSUE THREAD

**Issue by cswhjiang** [peteanderson80/Matterport3DSimulator#24]
It seems that the range of the camera elevation is [-PI/6, PI/6], not [-PI/2, PI/2] as mentioned in the paper. The value of ``state->elevation`` can only be ``-elevationIncrement``, ``elevationIncrement`` and 0.

https://github.com/peteanderson80/Matterport3DSimulator/blob/master/src/lib/MatterSim.cpp#L352-L361

**Comment by peteanderson80** [comment]
> The value of state->elevation can only be -elevationIncrement, elevationIncrement and 0.

Using discretized camera positions is an option. [Disable this option](https://github.com/peteanderson80/Matterport3DSimulator/blob/97bbfc4d90b7d809c21eb7998c4a3d8c083bf7cd/src/lib/MatterSim.cpp#L103-L107) if you want continuous camera motion.

> It seems that the range of the camera elevation is [-PI/6, PI/6], not [-PI/2, PI/2] as mentioned in the paper. 

The simulator can handle camera elevation range of [-PI/2, PI/2]. For our experiments with baseline seq2seq agents, we limit this to [-PI/6, PI/6].
