### ISSUE TITLE
ValueError: MatterSim: Invalid action index: 1

### ISSUE THREAD

**Issue by eric-xw** [peteanderson80/Matterport3DSimulator#27]
Hi @peteanderson80,

This error "ValueError: MatterSim: Invalid action index: 1" occurs sometimes during training.
I suspect this is a bug in the C++ code of your simulator. Say if the action is `forward`,  then the corresponding `env action` is (1, 0, 0), whose `index` is 1. Combining with you following c++ code:
```
void Simulator::makeAction(int index, double heading, double elevation) {
    totalTimer.Start();
    // move
    if (!initialized || index < 0 || index >= state->navigableLocations.size() ){
        std::stringstream msg;
        msg << "MatterSim: Invalid action index: " << index;
        throw std::domain_error( msg.str() );
    }
```
Then it basically means that the agent always chooses the `navigable location` whose index is 1. So if the size is less than or equal 1, then it raises the error. This seems an edge case (the agent chooses to go forward but there is no next `navigable location` to go).

Is my understanding correct? If so, how do you think the bug can be fixed? Thanks!

**Comment by peteanderson80** [comment]
Hi @littlekobe,

Thanks for the pull request. However, I don't think this is a problem with the simulator. If the input is a non-existent location index, throwing an error still seems like the correct response. So, I'm not sure about accepting that PR.

I think the problem must be with the agent (which should not be trying to navigate forwards when there is not navigable location). [These lines](https://github.com/peteanderson80/Matterport3DSimulator/blob/229af69ad059183f2bbf8358213ff9f054492255/tasks/R2R/agent.py#L240-L243) in the agent are supposed to mask invalid output actions before sampling from the agent's softmax. If this isn't working properly maybe it's a floating point issue?
