### ISSUE TITLE
Feature extraction

### ISSUE THREAD

**Issue by zwx8981** [peteanderson80/Matterport3DSimulator#34]
I see your feature extraction code and I have a question. The input image size is set to be 480X640 and this will results in that the shape of the output of pool5 layer of resnet152 to be BX2048X9X14. Why did you only slice the feature in a single spatial position [:, :, 0, 0] instead of averaging features across all spatial positions?

https://github.com/peteanderson80/Matterport3DSimulator/blob/229af69ad059183f2bbf8358213ff9f054492255/scripts/precompute_img_features.py#L124

**Comment by zwx8981** [comment]
Well, see the modification of prototxt

**Comment by peteanderson80** [comment]
Yes, the prototxt uses global average pooling.
