### ISSUE TITLE
How to get images from simulator?

### ISSUE THREAD

**Issue by balaramb** [peteanderson80/Matterport3DSimulator#36]
Hi, if we want to use our own image extractor, how do we get images (all 36 of them) from the simulator for a given viewpoint?

**Comment by peteanderson80** [comment]
There is an example of generating all 36 images at a given viewpoint [here](https://github.com/peteanderson80/Matterport3DSimulator/blob/5aeab4ae670c38bdbb15b1bcd9d2239069c37b1a/scripts/precompute_img_features.py#L97-L103).
