### ISSUE TITLE
Unable to download the R2R Dataset

### ISSUE THREAD

**Issue by YicongHong** [peteanderson80/Matterport3DSimulator#38]
Hi, access denied to download the R2R Dataset. could you please fix this?

--2019-02-24 19:23:10--  https://storage.googleapis.com/bringmeaspoon/R2Rdata/R2R_test.json
Resolving storage.googleapis.com (storage.googleapis.com)... 216.58.199.80, 2404:6800:4006:804::2010
Connecting to storage.googleapis.com (storage.googleapis.com)|216.58.199.80|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2019-02-24 19:23:11 ERROR 403: Forbidden.

Thanks!

**Comment by peteanderson80** [comment]
Apologies, the files got moved. Fixed in https://github.com/peteanderson80/Matterport3DSimulator/commit/31e7e3ed5927d38e03a71444073bcbbc98c462d8
