### ISSUE TITLE
sim.initialize() fails with EGL error 0x3001

### ISSUE THREAD

**Issue by srama2512** [peteanderson80/Matterport3DSimulator#39]
I was able to successfully perform a local installation of MatterSim without docker. However, running `driver.py` threw the following error:

```
Traceback (most recent call last):
  File "src/driver/driver.py", line 22, in <module>
    sim.initialize()
RuntimeError: EGL error 0x3001 at eglInitialize
```

My system configurations are as follows:
```
Ubuntu 16.04.5 LTS
Nvidia-driver version: 384.111
Cuda 9.0
CUDNN v7.1
```

**Comment by peteanderson80** [comment]
Any reason not to use the docker? In general I think it's going to be way easier to set up.

**Comment by srama2512** [comment]
The servers I use do not support docker, unfortunately. Also, I don't think there is an X-server running. I assumed that EGL rendering is headless (like OSMESA). However, the source code seems to require a display. Could that be the issue?

**Comment by peteanderson80** [comment]
The EGL rendering option will not need an X-server. We have tested that many times. 
I suspect this is related to your OpenGL / EGL install. There are some minimal EGL examples you could try, e.g. https://devblogs.nvidia.com/egl-eye-opengl-visualization-without-x-server/, it these can't run either then it's probably a missing library or something. You can check some of the dependencies in the readme and the dockerfile.

**Comment by srama2512** [comment]
I am unable to resolve this issue at the moment. I am precomputing the depth and using it with the v0.1 since that's easier for the time being. I'll close this for now. Thank you!

**Comment by cacoos** [comment]
Arriving a bit late!

Working on remote server and running a Flask app for showing images, importing `matplotlib` this way for showing images succeed for me:

```python
import matplotlib

matplotlib.use('WebAgg')

import matplotlib.pyplot as plt
```

**Comment by Mischievous707** [comment]
`Traceback (most recent call last):
  File "src/driver/driver.py", line 22, in <module>
    sim.initialize()
RuntimeError: EGL error 0x3001 at eglInitialize`

**Comment by shonnon-zxs** [comment]
I solve it by uninstall and install the Nvidia driver

**Comment by SinfulShell13** [comment]
sudo apt install xvfb
Xvfb :99 -screen 0 1024x768x24 &
export DISPLAY=:99
