### ISSUE TITLE
Do the simulators run in parallel in batch mode?

### ISSUE THREAD

**Issue by khanhptnk** [peteanderson80/Matterport3DSimulator#41]

**Comment by khanhptnk** [comment]
Are the simulators actually run in parallel in batch mode? If yes, is there any parameter to control the degree of parallelism?

**Comment by peteanderson80** [comment]
Not really, [each simulator is rendered and then the pixels read back sequentially](https://github.com/peteanderson80/Matterport3DSimulator/blob/8dcc5e5fa947092a5354a7300d9c50899eb0b03d/src/lib/MatterSim.cpp#L443-L492), so it's kinda dumb. This could probably be re-written to allow the gpu more opportunity to execute rendering calls in parallel. However the major bottleneck is actually loading textures on to the gpu as the agents move around.
