### ISSUE TITLE
Help, Error occur when i do the command "python src/driver/driver.py"

### ISSUE THREAD

**Issue by jingquanliang** [peteanderson80/Matterport3DSimulator#42]
Help, anyone can tell me the how to solve the below problem ??

GLib-GIO-Message: 00:41:33.081: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
OpenCV Error: Assertion failed (0 <= roi.x && 0 <= roi.width && roi.x + roi.width <= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= m.rows) in Mat, file /build/opencv-ys8xiq/opencv-2.4.9.1+dfsg/modules/core/src/matrix.cpp, line 323
Traceback (most recent call last):
  File "src/driver/driver.py", line 25, in <module>
    sim.newRandomEpisode(['17DRP5sb8fy'])
RuntimeError: /build/opencv-ys8xiq/opencv-2.4.9.1+dfsg/modules/core/src/matrix.cpp:323: error: (-215) 0 <= roi.x && 0 <= roi.width && roi.x + roi.width <= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= m.rows in function Mat

**Comment by chijames** [comment]
same error here :(

**Comment by philr-acvt** [comment]
I think this happens when you're missing the depth images. You can change the setDepthEnabled(true) call to setDepthEnabled(false) in the driver to skip loading them. Otherwise you'll have to download depth images and run the depth to skybox script.
