### ISSUE TITLE
Downloading matterport3d dataset too slow

### ISSUE THREAD

**Issue by ZhuFengdaaa** [peteanderson80/Matterport3DSimulator#44]
I am interested in vision-language navigation and want to download matterport3d and R2R datasets. However, 1.7T data is too large for me to download(around 10 days-time keeping 2MB/s downloading speed). 

I come to ask if I can train/test model under R2R setting with a small part of data like [MINOS](https://github.com/minosworld/minos), which is a dataset uses only 6.3GB data of matterport3d environment. 

https://github.com/niessner/Matterport/issues/26

**Comment by peteanderson80** [comment]
Many of the papers on this dataset are using the Precomputed ResNet Image Features (see links in the main readme), which can be downloaded in 3GB. 

Using these precomputed features, it is not necessary to download the Matterport dataset and you can also turn off rendering to speed up training (again, see main readme).

**Comment by ZhuFengdaaa** [comment]
@peteanderson80 Thanks for your helpful instruction. 

Another question. What to do if I want to visualize the behavior of my agent ?

**Comment by peteanderson80** [comment]
In the `web` folder there is some javascript code to create a first-person video of a trajectory through the environment. This will require downloading the Matterport skybox images though (not the entire Matterport dataset). 

Another good option is to load the textured meshes from the Matterport dataset in your favourite mesh viewer (e.g. meshlab) and then overlay your trajectory on this. There is also code in the Matterport dataset repo that has functions like this.

**Comment by ZhuFengdaaa** [comment]
@peteanderson80 According to your [paper of dataset](https://arxiv.org/pdf/1711.07280.pdf), rendering from panoramic images rather than textured meshes is better since the meshes have missing geometry. So what's the advantage of rendering in mesh? faster maybe ?
