### ISSUE TITLE
access state.rgb error

### ISSUE THREAD

**Issue by winnechan** [peteanderson80/Matterport3DSimulator#55]
I want to get RGB image for each angle views. However, when I want to access the image, the program failed. The error is listed below:

im = state.rgb 
TypeError: Unable to convert function return value to a Python type! The signature was
        (self: MatterSim.SimState) -> object

I compile the simulator with python 3.6.9, numpy 1.13.3 and opencv 3.1.0

**Comment by guhur** [comment]
What was your solution?

**Comment by RunweiSitu** [comment]
@winnechan Have you found a solution?
