### ISSUE TITLE
Image Extractor (ResNet-152) weight

### ISSUE THREAD

**Issue by yellowjs0304** [peteanderson80/Matterport3DSimulator#58]
Hi, Thank you for sharing nice work.
I want to extract RGB image directly.
Could you please share your Resnet-152 model (that you pretrained on ImagNet, and Finetune with places)?

Thank you.

**Comment by peteanderson80** [comment]
This model actually was not trained by us, it was the Resnet-152 model that was provided with the [Places dataset](https://github.com/CSAILVision/places365). Look for `ResNet152-places365 fine-tuned from ResNet152-ImageNet`.
