### ISSUE TITLE
Still have issue on "import mattersim"

### ISSUE THREAD

**Issue by yellowjs0304** [peteanderson80/Matterport3DSimulator#59]
hi, Thank you for continous project feedback.
i have trouble in docker environment.
After follow your readme script, I still have problem in doing `./scripts/**.py`.
`ModuleNotFoundError: No module named 'MatterSim' `
There was no problem in cmake process.

I did build several times as below commands.
```
- cmake -DEGL_RENDERING=ON ..
- cmake -DEGL_RENDERING=ON -DPYTHONPATH_EXECUTABLE=$PYTHONPATH
- cmake -DPYTHON_EXECUTABLE:FILEPATH=/home/[USERNAME]/anaconda3/envs/[ENVIRONMENT_NAME]/bin/[PYTHON_VERSION] ..
```

```
root@docker_env: echo $PYTHONPATH
declare -x PYTHONPATH="/root/mount/Matterport3DSimulator/build"
```
What should I do?
Thanks.

**Comment by yellowjs0304** [comment]
The problem is solved.
I deleted the container, and rerun.

**Comment by ShaoYULi12** [comment]
> 问题已经解决了。
> 我删除了容器，然后重新运行。

hi ~ i have the same problem. Could you please tell me the details about your solution.

**Comment by yellowjs0304** [comment]
@ShaoYULi12  I just deleted my docker container, and re-made a new one.
