### ISSUE TITLE
Small question for simulator API

### ISSUE THREAD

**Issue by jhchris713** [peteanderson80/Matterport3DSimulator#65]
Hi Everyone, 

I have problem in starting Simulator API section.
Following to the instruction, 
> import MatterSim
> sim = MatterSim.Simulator()
> sim.setCameraResolution(640, 480)
> sim.setPreloadingEnabled(True)
> sim.setDepthEnabled(True)
> sim.setBatchSize(100)
> sim.setCacheSize(200) # cacheSize 200 uses about 1.2GB of GPU memory for caching pano textures

How can I set these values??
Tried to do through command line in python, but the error occurs with
No Module named MatterSim.

As I am beginner, this question might be very stupid,
but don't know what to do from the fist start of the Simulator API.
Could someone give me a simple guideline to start this?
I would be really appreciate, because I am stucked in here for 4days..

Thanks.

**Comment by peteanderson80** [comment]
Did the steps to build the docker, build the code, and run the tests work ok?
https://github.com/peteanderson80/Matterport3DSimulator#building-and-testing-using-docker

**Comment by jhchris713** [comment]
> Did the steps to build the docker, build the code, and run the tests work ok?
> https://github.com/peteanderson80/Matterport3DSimulator#building-and-testing-using-docker

Yes,
I used the docker which you provided, the build compiled well.
(Or maybe not...
After making the new docker container, at the build stage after cmake, when I execute make command, following error occurs.
`/root/mount/Matterport3DSimulator/pybind11/include/pybind11/detail/common.h:111:10: fatal error: Python.h: No such file or directory
 #include <Python.h>
          ^~~~~~~~~~
compilation terminated.
`
However, removing existing build folder and remake the build folder with followings,

> cd /root/mount/Matterport3DSimulator
> mkdir build && cd build
> cmake -DEGL_RENDERING=ON ..
> make
> cd ../
> ./build/tests ~Timing

Everything works fine.
One question is during cmake, for python interpreter python 3.6 version is used and for numpy it includes from python 2.7 version. Is it okay?
`-- Found PythonInterp: /usr/bin/python3.6 (found version "3.6.9") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.6m.so
-- Performing Test HAS_CPP14_FLAG
-- Performing Test HAS_CPP14_FLAG - Success
-- pybind11 v2.2.1
-- Found PythonInterp: /usr/bin/python3.6 (found suitable version "3.6.9", minimum required is "3") 
/usr/bin/python3.6
-- Found NUMPY: /usr/lib/python2.7/dist-packages/numpy/core/include  
-- Found components for NumPy
-- NUMPY_ROOT_DIR    = /usr/local
-- NUMPY_INCLUDES    = /usr/lib/python2.7/dist-packages/numpy/core/include
-- NUMPY_LIBRARIES   = 
-- NUMPY_API_VERSION = 1.13.3
`
)

The docker was build with Off-screen GPU rendering using EGL.
One problem happened in running tests, but thought minor issue.
'./build/tests/ ~Timing' outputs All tests passed (119213 assertions in 5 test cases)
but, './build/tests/ Timing' gets killed in a few minutes.
Does './build/tests/ Timing' should be done?

**Comment by jhchris713** [comment]
run the commands through 'python3.6m' not 'python3.6'
