### ISSUE TITLE
opencv error according to opengl

### ISSUE THREAD

**Issue by jhchris713** [peteanderson80/Matterport3DSimulator#66]
With using docker image and container which you provided,
the opencv error occurs in following step.

> >xhost +
> nvidia-docker run -it -e DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix --mount type=bind,source=$MATTERPORT_DATA_DIR,target=/root/mount/Matterport3DSimulator/data/v1/scans,readonly --volume `pwd`:/root/mount/Matterport3DSimulator mattersim:9.2-devel-ubuntu18.04
> cd /root/mount/Matterport3DSimulator
> rm build
> mkdir build && cd build
> cmake ..
> make
> cd ../
> ./build/tests ~Timing

outputs following opencv error.

```
(renderwin:444): dbind-WARNING **: 10:25:05.263: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-zkWCnIqzb8: Connection refused
Gtk-Message: 10:25:05.282: Failed to load module "canberra-gtk-module"
Gtk-Message: 10:25:05.283: Failed to load module "canberra-gtk-module"
OpenCV Error: No OpenGL support (Library was built without OpenGL support) in cvNamedWindow, file /build/opencv-L2vuMj/opencv-3.2.0+dfsg/modules/highgui/src/window_gtk.cpp, line 1064

tests is a Catch v2.0.1 host application.
Run with -? for options

-------------------------------------------------------------------------------
RGB Image
-------------------------------------------------------------------------------
/root/mount/Matterport3DSimulator/src/test/main.cpp:342
...............................................................................

/root/mount/Matterport3DSimulator/src/test/main.cpp:350: FAILED:
  REQUIRE_NOTHROW( sim.initialize() )
due to unexpected exception with message:
  /build/opencv-L2vuMj/opencv-3.2.0+dfsg/modules/highgui/src/window_gtk.cpp:
  1064: error: (-218) Library was built without OpenGL support in function
  cvNamedWindow

===============================================================================
test cases:      5 |      4 passed | 1 failed
assertions: 119187 | 119186 passed | 1 failed
```

This issue was posted once before, but seems not figured.
[https://github.com/peteanderson80/Matterport3DSimulator/issues/33](33)

Without interactive demo, this issue seems minor issue.

**Comment by TopCoder2K** [comment]
@jhchris713, could you please share how you managed to cope with the problem?

**Comment by vdorbala** [comment]
I am facing the same issue, and can't use the docker image since I have a lot of other dependencies running. What is the solution for "OpenCV Error: No OpenGL support (Library was built without OpenGL support) in cvNamedWindow"?
