### ISSUE TITLE
AttributeError: 'MatterSim.Simulator' object has no attribute 'init'

### ISSUE THREAD

**Issue by rmant** [peteanderson80/Matterport3DSimulator#68]
When I try training the R2R baseline, I keep getting this error. Any reason why?

` File $PATH/Matterport3DSimulator/tasks/R2R/env.py", line 251, in make_sim
    sim.init()
AttributeError: 'MatterSim.Simulator' object has no attribute 'init'`

Thank you!

**Comment by peteanderson80** [comment]
You must be using an old version of env.py. Current version has no line 251 and doesn't call 'init'. The simulator API was updated a while back to support batching.

**Comment by rmant** [comment]
You were right, I was using an old version. Thank you!
