### ISSUE TITLE
issues on MatterSim

### ISSUE THREAD

**Issue by ShaoYULi12** [peteanderson80/Matterport3DSimulator#74]
I found that when i run the ./scripts/depth_to_skybox.py, an error appears below 
  File "./scripts/depth_to_skybox.py", line 25, in <module>
    from MatterSim import cbf
ModuleNotFoundError: No module named 'MatterSim'

**Comment by peteanderson80** [comment]
This can be solved by running the build instructions first.

**Comment by ShaoYULi12** [comment]
well i have rerun for several times.&nbsp; but it didn't work.&nbsp; it makes me crazy&nbsp; hhhhh



---Original---

**Comment by aishwaryap** [comment]
This doesn't work for me either after running build instructions. Running the build test resulted in this issue https://github.com/peteanderson80/Matterport3DSimulator/issues/83

**Comment by ygtreceee** [comment]
> This doesn't work for me either after running build instructions. Running the build test also fails with the following error (even though data files exist at data/v1/scans)
> 
> ```
> tests is a Catch v2.0.1 host application.
> Run with -? for options
> 
> -------------------------------------------------------------------------------
> RGB Image
> -------------------------------------------------------------------------------
> /root/mount/Matterport3DSimulator/src/test/main.cpp:342
> ...............................................................................
> 
> /root/mount/Matterport3DSimulator/src/test/main.cpp:373: FAILED:
>   REQUIRE_NOTHROW( sim.newEpisode(scanIds, viewpointIds, headings, elevations) )
> due to unexpected exception with messages:
>   [
>   	{
>   		"elevation" : 0.0085573808395640535,
>   		"heading" : 2.551961945320492,
>   		"reference_image" : "17DRP5sb8fy_85c23efeaecd4d43a7dcd5b90137179e_2.
>   551961945320492_0.008557380839564054.png",
>   		"scanId" : "17DRP5sb8fy",
>   		"viewpointId" : "85c23efeaecd4d43a7dcd5b90137179e"
>   	},
>   	{
>   		"elevation" : 0.00049218360228025842,
>   		"heading" : 1.8699330579409539,
>   		"reference_image" : "1LXtFkjw3qL_187589bb7d4644f2943079fb949c0be9_1.
>   8699330579409539_0.0004921836022802584.png",
>   		"scanId" : "1LXtFkjw3qL",
>   		"viewpointId" : "187589bb7d4644f2943079fb949c0be9"
>   	},
>   	{
>   		"elevation" : -0.024443526143047459,
>   		"heading" : 4.6263310475510773,
>   		"reference_image" : "1pXnuDYAj8r_163d61ac7edb43fb958c5d9e69ae11ad_4.
>   626331047551077_-0.02444352614304746.png",
>   		"scanId" : "1pXnuDYAj8r",
>   		"viewpointId" : "163d61ac7edb43fb958c5d9e69ae11ad"
>   	},
>   	{
>   		"elevation" : -0.00068389140394051673,
>   		"heading" : 5.8441199099264436,
>   		"reference_image" : "29hnd4uzFmX_1576d62e7bbb45e8a5ef9e7bb37b1839_5.
>   844119909926444_-0.0006838914039405167.png",
>   		"scanId" : "29hnd4uzFmX",
>   		"viewpointId" : "1576d62e7bbb45e8a5ef9e7bb37b1839"
>   	}
>   ]
>   MatterSim: Could not open skybox RGB files at: ./data/v1/scans//17DRP5sb8fy/
>   matterport_skybox_images/85c23efeaecd4d43a7dcd5b90137179e_skybox_small.jpg
> 
> ===============================================================================
> test cases:      5 |      4 passed | 1 failed
> assertions: 119188 | 119187 passed | 1 failed
> ```

hello, have you solved your problem ?
