### ISSUE TITLE
build/tests issue

### ISSUE THREAD

**Issue by ShaoYULi12** [peteanderson80/Matterport3DSimulator#79]
hi~ 
I found that when i run ./build/tests ~Timing，the error information is   
“MatterSim: Could not open skybox RGB files at: ./data/v1/scans//17DRP5sb8fy/
matterport_skybox_images/85c23efeaecd4d43a7dcd5b90137179e_skybox_small.jpg
test cases:      5 |      4 passed | 1 failed
assertions: 119188 | 119187 passed | 1 failed”.
So i download this dataset “17DRP5sb8fy”， and i try again. When i run "cmake -DEGL_RENDERING=ON ..", a new problem appears that 
"[ 90%] Building CXX object CMakeFiles/MatterSimPython.dir/src/lib_python/MatterSimPython.cpp.o
In file included from /home/share/lishaoyu/Matterport3D/Matterport3DSimulator/pybind11/include/pybind11/pytypes.h:12:0,
                 from /home/share/lishaoyu/Matterport3D/Matterport3DSimulator/pybind11/include/pybind11/cast.h:13,
                 from /home/share/lishaoyu/Matterport3D/Matterport3DSimulator/pybind11/include/pybind11/attr.h:13,
                 from /home/share/lishaoyu/Matterport3D/Matterport3DSimulator/pybind11/include/pybind11/pybind11.h:43,
                 from /home/share/lishaoyu/Matterport3D/Matterport3DSimulator/src/lib_python/MatterSimPython.cpp:1:
/home/share/lishaoyu/Matterport3D/Matterport3DSimulator/pybind11/include/pybind11/detail/common.h:111:10: fatal error: Python.h: No such file or directory
 #include <Python.h>
          ^~~~~~~~~~
compilation terminated.
CMakeFiles/MatterSimPython.dir/build.make:62: recipe for target 'CMakeFiles/MatterSimPython.dir/src/lib_python/MatterSimPython.cpp.o' failed
make[2]: *** [CMakeFiles/MatterSimPython.dir/src/lib_python/MatterSimPython.cpp.o] Error 1
CMakeFiles/Makefile2:183: recipe for target 'CMakeFiles/MatterSimPython.dir/all' failed
make[1]: *** [CMakeFiles/MatterSimPython.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2"
 thanks for your help!

**Comment by GalaxyS1ayer** [comment]
Hi, have you solved it，bro?I also encountered the same problem.MatterSim: Could not open skybox RGB files at: ../Matterport3DSimulator/data/v1/scans/17DRP5sb8fy/matterport_skybox_images/10c252c90fa24ef3b698c6f54d984c5c_skybox_small.jpg

**Comment by SuneoLi** [comment]
> Hi, have you solved it，bro?I also encountered the same problem.MatterSim: Could not open skybox RGB files at: ../Matterport3DSimulator/data/v1/scans/17DRP5sb8fy/matterport_skybox_images/10c252c90fa24ef3b698c6f54d984c5c_skybox_small.jpg

Hi, this might help you. I just solved the problem and add that comment https://github.com/peteanderson80/Matterport3DSimulator/issues/136#issuecomment-2367936322 .
