### ISSUE TITLE
"IndexError" occurs when using simulator API in Python. 

### ISSUE THREAD

**Issue by picksh** [peteanderson80/Matterport3DSimulator#96]
Hi, I am currently trying the Simulator. I am using the latest version and Building using Docker. Following the instructions, I passed all tests. However, when I try the Python API, there is a error:

>  IndexError: vector::_M_range_check: __n (which is 1) >= this->size() (which is 1)

for:

> sim.newEpisode(['2t7WUuJeko7'], ['1e6b606b44df4a6086c0f97e826d4d15'], [0], [0])

The full code is also attached:

     if __name__=='__main__':
        VFOV = math.radians(60)
        sim=MatterSim.Simulator()
        sim.setCameraResolution(640, 480)
        sim.setCameraVFOV(VFOV)
        sim.setPreloadingEnabled(True)
        sim.setDepthEnabled(False)
        sim.setBatchSize(100)
        sim.setCacheSize(200)  # cacheSize 200 uses about 1.2GB of GPU memory for caching pano textures
        sim.initialize()
        sim.newEpisode(['2t7WUuJeko7'], ['1e6b606b44df4a6086c0f97e826d4d15'], [0], [0])

I am using a headless machine with ubuntu18.04 and my gcc version is 7.5.0.
I think there might be some problem with "using python lists in place of C++ std::vectors" but just a guess and I can not fix it.
I would appreciate any infomation you could give me.

**Comment by jacobkrantz** [comment]
This line assumes a batch size of 1:
```python
sim.newEpisode(['2t7WUuJeko7'], ['1e6b606b44df4a6086c0f97e826d4d15'], [0], [0])
```
but earlier you set `sim.setBatchSize(100)`. The IndexError goes away for me when I use a proper batch size, in this case 1.

**Comment by picksh** [comment]
Thanks a lot!
